dist: xenial
language: python
cache: pip
python:
  - "3.7"
services:
  - postgresql
env:
  global:
  - SOURCE_FOLDER=gnosis
  - PIP_USE_MIRRORS=true
  - DJANGO_SETTINGS_MODULE=config.settings.test
addons:
  postgresql: "9.6"
install:
  - pip install -r requirements-test.txt
  - pip install coveralls
  - npm install -g ganache-cli@6.6.0
script:
  - ganache-cli -d -p 8545 --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --noVMErrorsOnRPCResponse > /dev/null &
  - sleep 5
  - coverage run --source=$SOURCE_FOLDER -m py.test -W ignore::DeprecationWarning -rxXs
after_success:
  - coveralls
deploy:
  provider: script
  script: bash scripts/deploy_pipy.sh "${PYPI_USER}" "${PYPI_PASS}"
  skip_cleanup: true
  on:
    tags: true
